name: Deploy to Production

on:
  push:
    tags:
      - '*'

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: [ self-hosted, docsqa ]

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ github.token }}
        lfs: 'true'
        clean: 'true'
        fetch-depth: 0
        
    - name: Pull NPM Dependencies
      run: |
        npm ci

    - name: Generate menu
      run: cat content/navigation.md | ./navigation2menu.js > config/_default/menu.en.json

    # Build the HTML versions of the md using hugo
    - name: Build WebChart HTML
      run: hugo --config 'config-wc.toml' --minify --baseURL https://docs.webchartnow.com/

    - name: Build Enterprise Health HTML
      run: hugo --config 'config-eh.toml' --minify --baseURL https://docs.enterprisehealth.com/

    - name: 'Deploy built documentation to production folder'
      run: |
        rsync -ruva public deploy@wc-docs.med-web.com:/www/docrootssl/docs

    - name: Rocket.Chat Notification
      uses: wreiske/Rocket.Chat.GitHub.Action.Notification@1.5.1
      if: always()
      with:
        type: ${{ job.status }}
        job_name: '*Publish to Production*'
        mention: 'here'
        channel: '#miedocs'
        url: ${{ secrets.ROCKETCHAT_WEBHOOK }}
        commit: true
        token: ${{ github.token }}
